name: CI / CD Pipeline

on:
  push:
    branches: [main] # main 브랜치에 push 될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Lint & Type Check
        run: |
          npm run lint
          npx tsc --noEmit

      # Vercel CLI Install
      - name: Install Vercel CLI
        run: npm install --global vercel

      # Vercel 환경 설정 가져오기 (해당 과정에서 .vercel 폴더 생성)
      - name: Pull Verce lEnvironment Information
        run: vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}}
        env:
          VERCEL_ORG_ID: ${{secrets.ORG_ID}}
          VERCEL_PROJECT_ID: ${{secrets.PROJECT_ID}}

      # Project Build (Production용 빌드 아티팩트 생성)
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{secrets.VERCEL_TOKEN}}

      # 빌드된 결과물을 Vercel로 배포 및 Production 승격
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}
